name: Merge main into develop

on:
  push:
    branches:
      - main

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: main -> develop
        uses: robotology/gh-action-nightly-merge@v1.3.1
        with:
          stable_branch: 'main'
          development_branch: 'develop'
          allow_ff: true
          user_name: uihyeon.cha
          user_email: uihyeon.cha@gmail.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
