name: Merge to develop

on:
  workflow_run:
    workflows: ['Auto Release']
    types:
      - completed
      - requested

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: main -> develop
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: develop
          github_token: ${{ github.token }}
